### ISSUE TITLE
64 bit version

### ISSUE THREAD

**Issue by tommyka** [espena/sosicon#1]
Its not possible to either compile or run the finished binary on debian 64bit

**Comment by espena** [comment]
I will look into that! Thanks.

**Comment by espena** [comment]
OK, problem solved. Turned out to be quite logical: A 64-bit version of the Ragel build tool was missing, hence Sosicon failed to compile. I have now supplied the missing executable and added a Linux 64-bit build configuration. The Linux output directory names are named linux32 and linux64.
